version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_DSN=myuser:mypassword@database:3306/mydatabase?parseTime=true
    ports:
      - 1323:1323
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    image: mariadb
    environment:
      - MARIADB_DATABASE=mydatabase
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_ROOT_PASSWORD=123
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork

networks:
  mynetwork: